### ISSUE TITLE
[Labels] Label endpoint missing loadResources() function

### ISSUE THREAD

**Issue by ridz1208** [aces/biobank#246]
Prod error
```[Fri Jul 28 08:45:04.777226 2023] [php:notice] [pid 3641] [client 192.168.122.1:58700] [CRITICAL] /var/www/loris/php/libraries/Module.class.inc:379: Uncaught Error: Call to undefined method LORIS\\biobank\\LabelEndpoint::loadResources() in /var/www/loris/php/libraries/Module.class.inc:379\nStack trace:\n#0 /var/www/loris/project/modules/biobank/php/module.class.inc(67): Module->handle()\n#1 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\biobank\\Module->handle()\n#2 /var/www/loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process()\n#3 /var/www/loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process()\n#4 /var/www/loris/src/Middleware/ExceptionHandlingMiddleware.php(54): LORIS\\Router\\ModuleRouter->handle()\n#5 /var/www/loris/src/Router/BaseRouter.php(133): LORIS\\Middleware\\ExceptionHandlingMiddleware->process()\n#6 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#7 /var/www/loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#8 /var/www/loris/htdocs/index.php(55): LORIS\\Middleware\\ContentLength->process()\n#9 {main}\n  thrown, referer: https://cbigr.loris.ca/biobank/barcode=COPN0000655013```

I temporarily added the function on production but it should be permanently fixed through a PR

**Comment by HenriRabalais** [comment]
PR created #247
